server:
  port: 8081
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

spring:
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 5000

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

bank-app-service:
  url: ${BANK_APP_URL:http://localhost:8080}